# Generated by Django 5.0.3 on 2024-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=20, unique=True)),
                ('vendor_fname', models.CharField(max_length=100)),
                ('vendor_lname', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('vendor_phone_number', models.CharField(max_length=20)),
                ('vendor_company_name', models.CharField(max_length=100)),
                ('vendor_gst_num', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor_company_type', models.CharField(max_length=20)),
                ('vendor_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
