# Generated by Django 5.0.3 on 2024-03-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('country_restrictions', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.TextField()),
                ('cutomer_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=12, unique=True)),
                ('firm_budgetary', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=100)),
                ('shape', models.CharField(max_length=100)),
                ('size_in_mm', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('material_need_date', models.DateField()),
                ('remarks', models.TextField()),
                ('material_created_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
            ],
        ),
    ]
